apiVersion: v1
kind: Service
metadata:
  name: argocd-server-np
  namespace: argocd
spec:
  type: NodePort
  ports:
    - name: http
      port: 80               # Port exposed inside the cluster
      targetPort: 8080        # ArgoCD service runs on this port
      nodePort: 30080         # Custom NodePort for external access (between 30000-32767)
  selector:
    app.kubernetes.io/name: argocd-server  # This ensures traffic is routed to the correct pod
