apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort  # Change to LoadBalancer for external load balancing
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # This will expose your app on port 30000 of the node
  selector:
    app: springboot-app

